#!/usr/local/bin/python3
# https://pypi.org/project/redis/
import redis, time
r = redis.Redis(host='redis', port=6379, db=0)

# Using redis pubsub, subscribe to channel "election2022"
# Whenever someone votes, report the latest vote tally
# from HSET "election2022votes".

# You should be able to run this in a terminal while voting in other terminals

# https://pypi.org/project/redis/ # See the Publish/Subscribe section
# in particular, you will have to build a polling loop


