#!/bin/bash
USAGE="Usage: $0 IP-Master IP-New"

if [ "$#" -ne "2" ]; then
	echo "$USAGE"
	exit 1
fi

MASTER="$1"

COMMAND="docker run --name cassandra-node --restart unless-stopped -v /home/student/cassData:/var/lib/cassandra -d -e CASSANDRA_BROADCAST_ADDRESS=$2 -p 7000:7000 -p 9042:9042 -e CASSANDRA_SEEDS=$MASTER cassandra"


ssh student@$2 "docker container stop cassandra-node; docker container rm cassandra-node; $COMMAND;"
	
	
	while true;
	do
		sleep 5
		STATUS=$(docker exec -it cassandra-node nodetool status | grep -e $2)
		STATUSUN=$(echo $STATUS | grep -e "UN")
		echo $STATUS
		[[ ! -z "$STATUSUN" ]] && break;
	done;

