version: "3"
services:
  web:
    image: python-app
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 0
        window: 10m  
#    volumes:
 #     - "/home/student/a2StarterCode/testStarter/docker/play:/play"
    ports:
      - "4000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      
    networks:
      - vote2022net
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - vote2022net
  redis-master:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
        # delay: 10s
        # max_attempts: 0
        # window: 10m
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - "/home/student/redisData:/data"  
    networks:
      - vote2022net 

  redis-slave:
    image: redis
    ports:
      - "6380:6379"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
        max_replicas_per_node: 1
        # delay: 10s
        # max_attempts: 0
        # window: 10m
    command: redis-server --bind 0.0.0.0 --port 6380 --replicaof redis-master 6379 --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vote2022net

networks:
  vote2022net:


