version: "3"
services:
  web:
    image: python-app
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - "/home/student/election2022/docker/play:/play"
    ports:
      - "4000:80"
    networks:
      - vote2022net
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - vote2022net
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/student/election2022/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - vote2022net 
networks:
  vote2022net:


