# Use the official Cassandra image as the base
FROM cassandra:latest

# Set any additional configurations or dependencies here if needed
# COPY cassandra.yaml /etc/cassandra/ # Uncomment if you need to copy a custom config file

# Expose Cassandra ports for communication
EXPOSE 9042 7000 7001 7199 9160
