# Use the official Redis image as the base
FROM redis:latest

# Optional: Set up a custom configuration file
# COPY redis.conf /usr/local/etc/redis/redis.conf # Uncomment if you want custom Redis configs

# Expose the Redis port
EXPOSE 6379
